# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b633f499b488d7b4b22024051fc37881f8a38cf8e3576d961b16ff9a97397b042d3d6a6007b91be6e4c9656b5c1c2a2e9dcb4dd8dc2eb18f4c0f9591c3dc8f5c

test:
  secret_key_base: 6c80ebae66be34e5c75d2e35bf52a31422df7dd717f87903764e49c50c30803d2206a298df3b8c07b3a1de2af5e8845ceb60f74532c7df317f3ec6aea7793b5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
